name: "Release EmbassyOS app package"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release-embassy-os:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Enable cross-arch emulated builds in docker
        run: docker run --privileged --rm linuxkit/binfmt:v0.8

      - name: Install dependencies
        run: |
          sudo snap install yq deno
          sudo apt-get install -y build-essential openssl libssl-dev libc6-dev clang libclang-dev ca-certificates    

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Build and install embassy-sdk
        run: |
          cd ~/ && git clone --recursive https://github.com/Start9Labs/embassy-os.git
          cd embassy-os/backend/
          ./install-sdk.sh
          embassy-sdk init

      - name: Clone the project locally
        uses: actions/checkout@v3
        with:
          path: tdex-wrapper

      - name: Build the tdex s9pk
        run: |
          cd tdex-wrapper
          make

      - uses: actions/upload-artifact@v3
        with:
          name: tdex.s9pk
          path: tdex.s9pk

